version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/app/.env
    networks:
      - ft_transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    
  backend:
    container_name: backend
    image: backend
    build: 
      context: ./backend/app
      dockerfile: dockerfile
    env_file:
      - ./backend/app/.env
    ports:
      - "4000:4000"
      - "4001:4001"
      - "5555:5555"
    depends_on:
      - postgres
    networks:
      - ft_transcendence
    restart: always

  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    networks:
      - ft_transcendence

volumes:
  postgres_data:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/data

networks:
  ft_transcendence:
    driver: bridge